swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img src="data:text/javascript,alert(1)"> 
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
