swagger: "2.0"
info:
  title: "Login API"
  description: |
    <form action="/login" method="POST">
      <h1>Login Form</h1>
      <label for="username">Username:</label>
      <input type="text" id="username" name="username"><br><br>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password"><br><br>
      <button type="submit">Login</button>
    </form>
    <script>alert('This is an HTML injection');</script>
  version: "1.0.0"
host: "157.230.93.64:8000"
basePath: "/api"
paths:
  /login:
    post:
      summary: "Submit login credentials"
      description: "This is a login endpoint"
      parameters:
        - name: "username"
          in: "formData"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
