swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img src="jAvAsCrIpT&colon;alert&lpar;1&rpar;"> 
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
