swagger: "2.0"
info:
  title: "Fake Login API"
  description: |
    <h1>Fake Login</h1>
    <input/>
  version: "1.0.0"
host: "7aipbt3u1ve1hubyvslu0v8qhhn9bzzo.oastify.com"
basePath: "/api"
paths:
  /login:
    post:
      summary: "Submit login credentials"
      description: "This is a login endpoint"
      parameters:
        - name: "username"
          in: "formData"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
