swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img/src/onerror=.1|alert``>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
